# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;
      - name: build
        run: docker-compose build



  login:
    needs: [ build ]
    steps:
      - name: login to dockerhub
        run: docker login
        env:
          login: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}

  push:
    needs: [ login ]
    steps:
      - name: docker push
        run: docker images
      - name: docker push
        run: docker tag apl_web:latest jesesok/apl_web:latest
      - name: docker push
        run: docker push jesesok/apl_web:latest