# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: alex-ac/github-action-ssh-docker-compose@master
        with:
          ssh_host: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE }}
          ssh_user: ${{ secrets.EXAMPLE_COM_SSH_USER }}
          docker_compose_prefix: example_com
