name: Connect
on:
  push:
    branches: [ master, deploy ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd APL/ && git pull && docker-compose build && docker-compose up -d

